---
title: "Bibilashvili_Filan"
output: html_notebook
---
```{r}
setwd("C:/Users/user/Desktop/R studio Final eXam")
winLose<-read.csv("winLose.csv")
library("ggplot2")
library("stargazer")
library("knitr")

```

```{r}
summary(subset(winLose, select =c("chalwin4","relcapbl","rlstake3","relres4","chalnuke","defnukes","chaldemc","defdemoc")))
```

```{r}
countOfConflicts <- table(winLose$year)
```

```{r}
countOfConflictsPerYear <- as.data.frame(countOfConflicts)
names(countOfConflictsPerYear)[1] = 'year'
names(countOfConflictsPerYear)[2] = 'countOfConflicts'
```

```{r}
ggplot(countOfConflictsPerYear, aes(x=year, y=countOfConflicts, group=1))+
geom_line(linetype=1, color="#339999", size=1)+
geom_point(color="#ff6e00")+
scale_x_discrete(breaks=c(1920, 1930,1935, 1940, 1950, 1960, 1970, 1980, 1990))+
labs(title="Number of International Conflicts, 1918-1994",
x="Year",
y="Number of Conflicts")
#the line of diagram shows number of conflicts per-year, and first part of 20th century is peacful compere to other years 
```

```{r}
countOfChallengerPrevails <- table(winLose$chalwin4[winLose$chalwin4==1 | winLose$chalwin4==4])
names(countOfChallengerPrevails)[1] = 'lose'
names(countOfChallengerPrevails)[2] = 'win'
countOfChallengerPrevails
```

```{r}
mean(winLose$chaldemc[winLose$chalwin4==1], na.rm = TRUE)#lose
mean(winLose$chaldemc[winLose$chalwin4==2], na.rm = TRUE)#stalemate
mean(winLose$chaldemc[winLose$chalwin4==3], na.rm = TRUE)#compromise
mean(winLose$chaldemc[winLose$chalwin4==4], na.rm = TRUE)#win
#6.4 score if average democracy
#7.1 deadlock
#8.7when comprised
#9.2 when won 
```

```{r}
mean(winLose$chaldemc, na.rm = TRUE)#Challenger's Democracy Score
mean(winLose$defdemoc, na.rm = TRUE)#Defender's Democracy Score
```

```{r}
ggplot(winLose,aes(x=factor(chalnuke),y=chaldemc)) + 
  geom_boxplot()+
  labs(title="", x="Challenger Nuclear Capable ", y="Challenger's Democracy Score")
#this shows democracy chellenger countries, who have nuclear weapon, and differ from those who have not nuclear weapons. This diagram protreis differene between non-nuclear and nuclear states. 
```

```{r}
t.test(chaldemc~chalnuke,winLose)
#p-value is too low, therefore we can assume that there is difference between groups 
```

```{r}
winLose$relres4[winLose$relres4 < 0] <- NA
#Transforming the variable relres4. Changeing negative values to NA
```

```{r}
chalWinLose <-winLose[winLose$chalwin4==1 | winLose$chalwin4==4,]
#new dataframe which contains only won and lost conflicts by the challengers
```

```{r}
winLose$defWin4[winLose$chalwin4==1] <- 4
winLose$defWin4[winLose$chalwin4==2] <- 2
winLose$defWin4[winLose$chalwin4==3] <- 3
winLose$defWin4[winLose$chalwin4==4] <- 1
```

```{r}
table(chalWinLose$chalwin4)
```

```{r}
ggplot(chalWinLose,aes(x=factor(chalwin4),y=chaldemc)) + 
 geom_boxplot()
```

```{r}
#dividing countries by democracy score (>=15 as democratic, <15 as nondemocratic)
demChal <- winLose[winLose$chaldemc >= 15,]
nonDemChal <- winLose[winLose$chaldemc < 15,]

demDef <- winLose[winLose$defdemoc >= 15,]
nonDemDef <- winLose[winLose$defdemoc < 15,]

table(demChal$chalwin4)
table(nonDemChal$chalwin4)
table(demDef$chalwin4)
table(nonDemDef$chalwin4)
#proportion of win/lose for democratic states are high
#Democratic Challenger win/lose - 27/23 Non-democratic 59/146
#Democratic Defender win/lose - 39/75 Non-democratic 47/93
```

```{r}
chalDefDemScore <- lm(chalwin4~chaldemc+defdemoc, chalWinLose)
summary(chalDefDemScore)
```

```{r}
ggplot(winLose, aes(x=relcapbl, y=chaldemc))+
geom_point(aes(colour=rlstake3))+
geom_smooth(method="lm")+
labs(title="",
x="Relative Military Capabilities",
y ="Challangers democracy score",color = "Relative interests at stake")

ggplot(winLose, aes(x=relcapbl, y=defdemoc))+
geom_point(aes(colour=rlstake3))+
geom_smooth(method="lm")+
labs(title="",
x="Relative Military Capabilities",
y ="Defenders democracy score",color = "Relative interests at stake")
```
```{r}
militaryCap <- lm(relcapbl~chaldemc+defdemoc+rlstake3, winLose)
summary(militaryCap)
```

```{r}
ggplot(winLose, aes(x=chalwin4, y=relcapbl))+
geom_point(aes(colour=chaldemc,size=rlstake3))+
#geom_smooth(method="lm")+
labs(title="",
x="Challenger Win/Lose",
y ="Challengrers Military Capabilities",color = "Democracy Score",size= "Relative interests at stake")
#in this case we can assume that democracy score is lower, when challenger lose, and also chellenger states are most prevail. 
```

```{r}
ggplot(winLose, aes(x=defWin4, y=relcapbl))+
geom_point(aes(colour=defdemoc ,size=rlstake3))+
#geom_smooth(method="lm")+
labs(title="",
x="Deffender Win/Lose",
y ="Deffender's Military Capabilities",color = "Democracy Score",size= "Relative interests at stake")
#in this 2 cases difference of democracy are not high,democratic countries are more likely to win either as challengers or as offenders is not true.



```

```{r}
mean(demChal$rlstake3[demChal$chalwin4==4],na.rm = TRUE)#win
mean(demChal$rlstake3[demChal$chalwin4==1],na.rm = TRUE)#lose
mean(nonDemChal$rlstake3[nonDemChal$chalwin4==4],na.rm = TRUE)#win
mean(nonDemChal$rlstake3[nonDemChal$chalwin4==1],na.rm = TRUE)#lose
#there's no much difference in interest rates
```

```{r}
mean(demChal$relcapbl[demChal$chalwin4==4],na.rm = TRUE)#win
mean(demChal$relcapbl[demChal$chalwin4==1],na.rm = TRUE)#lose
mean(nonDemChal$relcapbl[nonDemChal$chalwin4==4],na.rm = TRUE)#win
mean(nonDemChal$relcapbl[nonDemChal$chalwin4==1],na.rm = TRUE)#lose
#this factors don't have an impact on outcome, we can say that ot;s coming from democratic model 
```


```{r}
plot(cars)
```

