---
title: "Class 3"
output:
  html_document: default
  html_notebook: default
---
```{r}
elist<-c("I'm the first element", "I m the second element", "I 
m the third element")


```

Germany

```{r}
plot(cars)
```

```{r}
TSU<-list(c(1918),c("SP", "PSY", "EB", "H", "L", "Sc"),c(40000), c("1st", "9th", "Maghlivi"))

attr(TSU,"Attribute")<-"Here I store information about TSU!"
attributes(TSU)

human <-c(22,165,75)

names(human) <-c ("Age", "Height", "Weight")

names(human)

eyes<-factor(c(1,2,3,4), levels=c("Brown", "Green", "Blue", "Grey"))


humans <-data.frame(
  human.id=c(1:3),
  human.name =c("Rati", "Dato", "Tsisana"),
  human.soft =c("Stata","PYTHON", "SPSS"),
  human.age =c(28, 29, 30),
  stringsAsFactors = FALSE
)

humans[which(humans$human.name == "Rati" |humans$human.name=="Tsisana"), ]

```








Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
